config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :home, only: [:index] do
    post :gacha, on: :collection
    get :debug, on: :collection
  end

  resources :players, only: [:edit, :update] do
    post :init, on: :collection
  end

  resources :countries, only: [:index,:show,:edit,:update]

  resources :trades, except: [:new] do
    post :buy, on: :member
  end

  resources :letters, only: [:index,:show,:new,:create] do
    post :accept, on: :member
    post :reject, on: :member
    post :open_present, on: :member
  end

  resources :cards, only: [] do
    get  :improve,   on: :member
    post :improving, on: :collection
    get  :trade,     on: :member
  end

  root to: "home#index"

end

app/models/card.rb
class Card < ActiveRecord::Base
  belongs_to :player
  has_one :trade

  def data
    CARDS[self.data_id]
  end

  def have_effect?(key)
    nil
  end

  def effect(key)
    nil
  end

  # in 材料となるカードの配列
  def improve(cards)
    exp = 0
    cards.each do |c|
      exp += c.level
      exp += c.level if(c.type == self.type)
    end
    self.levelup(exp)
  end

  def levelup(exp)
    exp += self.exp
    [20,60].each_with_index do |pt, level|
      if(self.level == level+1 && exp >= pt)
        self.level += 1
        exp -= pt
      end
    end
    self.exp = exp
    self.save
  end

  def era_status
    return "suitable" unless(self.player)
    return "too_early" if(self.era > self.player.era)
    "suitable"
  end

  def name
    self.data.name
  end

  def type
    self.data.type
  end

  def power
    self.data.power
  end

  def rerity
    self.data.rerity
  end

  def era
    self.data.era
  end
end

app/models/card_data.rb
class CardData

attr_accessor :id
attr_reader :name, :type, :power, :era, :rerity

end

app/models/catalog.rb
class Catalog < ActiveRecord::Base
  belongs_to :player
end

app/models/country.rb
# encoding: utf-8

class Country < ActiveRecord::Base
  validates_presence_of :name
  validates_uniqueness_of :name
  belongs_to :player

  def init
    self.name = init_name
    # 全ての国の座標配列
    countries = Country.all.map{|country| [country.x,country.y]}

    1000.times do 
      x = rand(16)
      y = rand(16)
      unless(countries.include?([x,y]))
        self.x = x
        self.y = y
        self.save
        break
      end

    end
    self.save
  end

  def init_name
    ["大","神聖","第","大いなる","","",""].sample + self.id.to_s + ["番","","",""].sample + ["国","王国","帝国","共和国","騎士領","連邦","公国"].sample
  end

  def distance(opp_country)
    (Math::sqrt((self.x - opp_country.x) ** 2 + (self.y - opp_country.y) ** 2)).round(2)
  end
end

app/models/letter.rb
# encoding: utf-8

class Letter < ActiveRecord::Base

  def converted_subject
    subject = self.subject
    case(self.ltype)
    when "letter"
      subject
    when "treaty"
      "条約「#{subject}」の提案"
    when "treaty_of_commerce"
      "相互通商条約の提案"
    when "send_money"
      "送金: #{text}"
    when "send_card"
      card = Card.find(text)
      "カードの送信: #{card.name}(Lv#{card.level})"
    end
  end

  def your_letter?(player)
    self.player_id == player.id
  end

  def treaty?
    (self.ltype == "treaty" || self.ltype == "treaty_of_commerce")
  end

  def l_present?
    (self.ltype == "send_money" || self.ltype == "send_card")
  end

  def given_or_sent(player)
    (your_letter?(player)) ? "sent" : "given"
  end

  def accepted_j
    self.accepted ? "受諾" : "拒否"
  end

end

app/models/log.rb
class Log < ActiveRecord::Base
end

app/models/management.rb
# encoding: utf-8

class Management < ActiveRecord::Base
  belongs_to :player

  def actual_max
    self.max - self.damage
  end

  def levelup
    if(self.exp >= (self.max+1)/2)
      self.exp -= (self.max+1)/2
      self.max += 1
      self.save
      self.player.private_logs.create(text: "最大内政力が#{self.max}になりました")
    end
  end
end

app/models/money.rb
class Money < ActiveRecord::Base
  belongs_to :player

  def add(v)
    self.pt += v
    self.save
  end

  # マイナスになったときのことは後で考える
  # 基本的にはマイナスになる操作を行わないようにする
  def sub(v)
    self.pt -= v
    self.save
  end
end

app/models/player.rb
# encoding: utf-8

class Player < ActiveRecord::Base
  validates_presence_of :name
  validates_uniqueness_of :name
  belongs_to :user
  has_many :cards
  has_one :management
  has_one :money
  has_one :country
  has_many :catalogs
  has_many :trades
  has_many :private_logs

  def init
    self.create_management(max: 6, pt: 6)
    self.create_money(pt: 100)
    self.create_country(name: "temp#{rand(100000)}")
    self.country.init
  end

  def card_limit
    limit = 7
    limit += self.catalogs.size
    self.cards.each do |card|
      limit += card.effect(:expand_card_limit) if card.have_effect?(:expand_card_limit)
    end
    limit
  end

  def era
    if(self.management.max >= 18)
      3
    elsif(self.management.max >= 14)
      2
    elsif(self.management.max >= 9)
      1
    else
      0
    end
  end
  
  def era_j
    ["古代","中世","近代","現代"][era]
  end

  def gacha(times)
    times = times.to_i
    return :over_card_limit if(card_limit < self.cards.size+times)
    return :less_management if(self.management.pt < times)

    cards = []
    times.times do 
      card = self.cards.create(data_id: rand(CARDS.size))
      cards.push card
    end

    man = self.management
    man.pt -= times
    man.exp += times
    man.levelup
    man.save

    catalogs = self.catalogs.map{|c|c.resource_id}
    cards.each do |card|
      self.catalogs.create(resource_id: card.data_id) if(card.type == :resource && !catalogs.include?(card.data_id))
    end
    cards
  end

  def maximize_management
    self.management.pt = self.management.max
    self.management.save
  end

end

app/models/private_log.rb
class PrivateLog < ActiveRecord::Base
  belongs_to :player
end

app/models/trade.rb
class Trade < ActiveRecord::Base
  belongs_to :player
  belongs_to :card
  default_scope { where(closed: false) } 

end

app/models/treaty.rb
class Treaty < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_one :player


  def init
    player = self.create_player(name: "temp#{rand(100000)}")
    player.init
  end

end

app/helpers/cards_helper.rb
module CardsHelper

  def card_name_to_data_id(str)
    CARDS.each do |c|
      return c.id if(c.name == str)
    end
  end

  def card_name_to_data(str)
    CARDS.each do |c|
      return c if(c.name == str)
    end
  end

end

app/helpers/countries_helper.rb
module CountriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
  include TradesHelper

  def max_addable_card_size
    [@player.management.pt, @player.card_limit-@player.cards.size].min
  end

  def trading_cards
    trades = @player.trades.map{|c|c.card_id}
    return Card.where(id: trades)
  end
end

app/helpers/letters_helper.rb
module LettersHelper

  def mark_letter_read
    @letters.each do |l,c|
      next if(l.ltype != "letter" || l.player_id == @player.id)
      l.read = true
      l.save
    end
  end

end

app/helpers/players_helper.rb
module PlayersHelper
end

app/helpers/trades_helper.rb
module TradesHelper

  def verify_creating(player, params)
  end

  def verify_buying(player, trade)
  end

end

app/helpers/treaties_helper.rb
module TreatiesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Gachalization</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= bootstrap_flash %>
<% if user_signed_in? %>
<div class="container">
<div class="row">
<div class="col-md-8">
<%= yield %>
</div>
<div class="col-md-4">
<% if @player %>
<%= render partial: "shared/sidebar" %>
<% end %>
</div>
</div>
</div>
<% else %>

<%= yield %>

<% end %>
</body>
</html>

app/views/shared/_init.html.slim
h1 初期設定
=form_tag(:init_players) do 
  div class="field"
    | プレイヤー名(必須)
    =text_field_tag :player_name
  div class="field"
    | 文明の名前(必須)
    =text_field_tag :country_name
  div class="field"
    | コメント
    =text_field_tag :comment
  div class="action"
    =submit_tag

app/views/shared/_sidebar.html.slim
H2 sidebar
div class="sidebar"
  =link_to "ログアウト", destroy_user_session_path, :method => :delete
  br
  b #{@player.name}
  =link_to "変更", edit_player_path(@player)
  br
  b #{@player.country.name}
  =link_to "変更", edit_country_path(@player.country)
  br
  i =country_comment(@player.country)
  br
  =link_to "トップ ", :root
  =link_to "交易 ", :trades
  =link_to "文明 ", :countries
  =link_to "書簡 ", :letters
  br
  | 内政力: #{@player.management.pt}/#{@player.management.actual_max}(最大#{@player.management.max},ダメージ#{@player.management.damage})
  br
  | exp: #{@player.management.exp}/#{(@player.management.max+1)/2}
  br
  span class="money" 資金: #{@player.money.pt} 
  span class="era" 時代: #{@player.era_j}
  br
  | カード: #{@player.cards.size}/#{@player.card_limit} 資源発見数: #{@player.catalogs.size}/#{all_number_of_resource}
  br
  br
  - @player.private_logs.order("created_at DESC").each do |log|
    p =log.text
  =link_to "デバッグ用", :debug_home_index