config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :home, only: [:index] do
    post :gacha, on: :collection
    get :debug, on: :collection
  end

  resources :players, only: [:edit, :update] do
    post :init, on: :collection
  end

  resources :countries, only: [:index,:show,:edit,:update]

  resources :trades, except: [:new] do
    post :buy, on: :member
  end

  resources :letters, only: [:index,:show,:new,:create] do
    post :accept, on: :member
    post :reject, on: :member
    post :open_present, on: :member
  end

  resources :cards, only: [] do
    get  :improve,   on: :member
    post :improving, on: :collection
    get  :trade,     on: :member
  end

  root to: "home#index"

end

app/models/letter.rb
# encoding: utf-8

class Letter < ActiveRecord::Base

  def converted_subject
    subject = self.subject
    case(self.ltype)
    when "letter"
      subject
    when "treaty"
      "条約「#{subject}」の提案"
    when "treaty_of_commerce"
      "相互通商条約の提案"
    when "send_money"
      "送金: #{text}"
    when "send_card"
      card = Card.find(text)
      "カードの送信: #{card.name}(Lv#{card.level})"
    end
  end

  def your_letter?(player)
    self.player_id == player.id
  end

  def treaty?
    (self.ltype == "treaty" || self.ltype == "treaty_of_commerce")
  end

  def l_present?
    (self.ltype == "send_money" || self.ltype == "send_card")
  end

  def given_or_sent(player)
    (your_letter?(player)) ? "sent" : "given"
  end

  def accepted_j
    self.accepted ? "受諾" : "拒否"
  end

end

app/controllers/letters_controller.rb
class LettersController < ApplicationController
include LettersHelper
before_action :authenticate_user!
before_action :preparing
after_action  :mark_letter_read, only: [:index]

  def index
    pid = @player.id
    @letters = []
    @sent_letters = Letter.where(player_id: pid)
    @given_letters = Letter.where(opp_id: pid)
    @given_countries = Country.where(id: @sent_letters.map{|l|l.opp_id}).pluck(:name)
    @sent_countries = Country.where(id: @given_letters.map{|l|l.player_id}).pluck(:name)
    temp_letters = @sent_letters+@given_letters
    temp_countries = @given_countries+@sent_countries

    # 手紙の内容と、その送り主/宛先を合体させ、時間に昇順に並べる
    (@sent_letters.size+@given_letters.size).times do |i|
      @letters.push [temp_letters[i],temp_countries[i]]
    end
    @letters.sort!{|a,b|b[0].created_at <=> a[0].created_at}

  end

  def show
  end

  def new
    @countries = Country.all.pluck(:name,:id)
    @countries.delete([@player.country.name,@player.country.id])
    @cards = @player.cards
    @cards = @cards.map{|c|["#{c.name}(Lv#{c.level},#{c.exp}exp)"]}
  end

  def create
    opp_id = Country.find(params[:country_id]).player.id
    text = params[:type] == "send_card" ? params[:card_id] : params[:text]
    Letter.create(player_id: @player.id, opp_id: opp_id, subject: params[:subject], text: text, ltype: params[:type])
    redirect_to :letters
  end

  def accept
    letter = Letter.find(params[:id])
    if(letter.ltype == "treaty")
      Treaty.create(player_id: letter.player_id, opp_id: letter.opp_id, name: letter.subject, text: letter.text)
    elsif(letter.ltype == "treaty_of_commerce")
      Treaty.create(player_id: letter.player_id, opp_id: letter.opp_id, commerce: true)
    end
    letter.accepted = true
    letter.read = true
    letter.save
    redirect_to :letters
  end

  def reject
    letter = Letter.find(params[:id])
    letter.accepted = false
    letter.read = true
    redirect_to :letters
  end

  def open_present
    letter = Letter.find(params[:id])
    if(letter.ltype == "send_money")
      Player.find(letter.opp_id).money.add(letter.text.to_i)
    elsif(letter.ltype == "send_card")
      card = Card.find(letter.text.to_i)
      card.update_attribute(:player_id, letter.opp_id)
    end
    letter.read = true
    letter.save
    redirect_to :letters
  end
end

app/helpers/letters_helper.rb
module LettersHelper

  def mark_letter_read
    @letters.each do |l,c|
      next if(l.ltype != "letter" || l.player_id == @player.id)
      l.read = true
      l.save
    end
  end

end

app/views/letters/index.html.slim
H1 書簡
=link_to "書簡を作成", :new_letter
br
=link_to "戻る", :root

table border=1
  tr
    th
    th 文明
    th 内容
    th 日時
    th 
  - @letters.each do |letter,country|
    tr class="#{letter.given_or_sent(@player)}"
      td
        - unless letter.read
          | new
      td 
        - if letter.your_letter?(@player)
          | to #{country}
        - else
          | from #{country}
      td =link_to letter.converted_subject, letter_path(letter)
      td #{letter.created_at}
      td
        - if !letter.your_letter?(@player)
          - if letter.treaty?
            - if letter.read
              | #{letter.accepted_j}
            - else
              =link_to "受諾 ", accept_letter_path(letter), method: :post
              =link_to "拒否", reject_letter_path(letter), method: :post
          - elsif letter.l_present?
            - if letter.read
              | 受け取り済み
            - else
              = link_to "受け取る", open_present_letter_path(letter), method: :post
        - else
          - if letter.treaty?
            - if letter.read
              | #{letter.accepted_j}
            - else
              | 受諾待ち

app/views/letters/new.html.slim
H1 書簡作成

= form_tag :letters do
  div
    span 宛先
    = select_tag :country_id, options_for_select(@countries)
  div
    span タイプ
    = select_tag :type, options_for_select([["書簡","letter"],["条約の提案","treaty"],["相互通商条約の提案","treaty_of_commerce"],["送金","send_money"],["カードを送る","send_card"]])
  div
    span カード
    = select_tag :card_id, options_for_select(@cards)
  div
    span タイトル(条約の名前)
    = text_field_tag :title
  div
    p 内容
    = text_area_tag :text, "", size: "70x6"
  div
    = submit_tag "送信"

app/views/letters/show.html.slim
h1 Letters#show
p Find me in app/views/letters/show.html.slim