config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :home, only: [:index] do
    post :gacha, on: :collection
    get :debug, on: :collection
  end

  resources :players, only: [:edit, :update] do
    post :init, on: :collection
  end

  resources :countries, only: [:index,:show,:edit,:update]

  resources :trades, except: [:new] do
    post :buy, on: :member
  end

  resources :letters, only: [:index,:show,:new,:create] do
    post :accept, on: :member
    post :reject, on: :member
    post :open_present, on: :member
  end

  resources :cards, only: [] do
    get  :improve,   on: :member
    post :improving, on: :collection
    get  :trade,     on: :member
  end

  root to: "home#index"

end

app/models/card.rb
class Card < ActiveRecord::Base
  belongs_to :player
  has_one :trade

  def data
    CARDS[self.data_id]
  end

  def have_effect?(key)
    nil
  end

  def effect(key)
    nil
  end

  # in 材料となるカードの配列
  def improve(cards)
    exp = 0
    cards.each do |c|
      exp += c.level
      exp += c.level if(c.type == self.type)
    end
    self.levelup(exp)
  end

  def levelup(exp)
    exp += self.exp
    [20,60].each_with_index do |pt, level|
      if(self.level == level+1 && exp >= pt)
        self.level += 1
        exp -= pt
      end
    end
    self.exp = exp
    self.save
  end

  def era_status
    return "suitable" unless(self.player)
    return "too_early" if(self.era > self.player.era)
    "suitable"
  end

  def name
    self.data.name
  end

  def type
    self.data.type
  end

  def power
    self.data.power
  end

  def rerity
    self.data.rerity
  end

  def era
    self.data.era
  end
end

app/controllers/cards_controller.rb
# encoding: utf-8

class CardsController < ApplicationController
  include CardsHelper
  before_action :authenticate_user!
  before_action :preparing

  def improve
    @target = Card.find(params[:id])
    return if error?(card_level_max_err(@target), :root)
    @others = @player.cards.reject{|c|c == @target}
  end

  def improving
    cards = Card.where(id: [params[:target]]+params[:card_id])
    return if error?(validate_cards_owner(cards), improve_card_path(params[:target]))
    cards = cards.to_a
    target = cards.delete_at(0)
    return if error?(target.level == 3 ? :levelmax : nil, :root)
    target.improve(cards)
    Card.where(id: cards.map{|c|c.id}).delete_all
    redirect_to :root, notice: "改良しました"
  end

  def trade
    @target = Card.find(params[:id])
  end

private

  def validate_cards_owner(cards)
    return :not_your_card if(cards.select{|c|c.player != @player}.size > 0)
  end

  def card_level_max_err(card)
    card.level == 3 ? :level_max : nil
  end

end

app/helpers/cards_helper.rb
module CardsHelper

  def card_name_to_data_id(str)
    CARDS.each do |c|
      return c.id if(c.name == str)
    end
  end

  def card_name_to_data(str)
    CARDS.each do |c|
      return c if(c.name == str)
    end
  end

end

app/views/cards/_card.html.slim
div class = "#{card.type}"
  span class="#{card.era_status}" 
    =card.name 
  | Lv.#{card.level} (#{card.exp}/#{[20,60,100][card.level-1]})
  br
  - if(card.type == :army)
    span pow #{card.power}
  - if(params[:action] == "improve" && @target.id != card.id)
    div =check_box_tag 'card_id[]', card.id
  - if(params[:action] != "improve")
    br
    - if(card.era_status == "suitable")
      =link_to "改良", improve_card_path(card.id)
    - else
      s 改良
    =link_to "交易", trade_card_path(card)

app/views/cards/improve.html.slim
h1 改良

div
  p このカードを改良します
  = render partial: @target
  div class="clearfloat"
div
  p 改良に使うカードを選択してください
  = form_tag :improving_cards, class: "improve"
    = render partial: :card, collection: @others
    = hidden_field_tag "target", @target.id
    div class="clearfloat"
    = submit_tag "改良"

app/views/cards/trade.html.slim
h1 カードを交易に出す

= render partial: @target

=form_tag(:trades) do 
  p 価格
  =text_field_tag :price
  =hidden_field_tag "card_id", @target.id
  =submit_tag "交易に出す"