config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :home, only: [:index] do
    post :gacha, on: :collection
    get :debug, on: :collection
  end

  resources :players, only: [:edit, :update] do
    post :init, on: :collection
  end

  resources :countries, only: [:index,:show,:edit,:update]

  resources :trades, except: [:new] do
    post :buy, on: :member
  end

  resources :letters, only: [:index,:show,:new,:create] do
    post :accept, on: :member
    post :reject, on: :member
    post :open_present, on: :member
  end

  resources :cards, only: [] do
    get  :improve,   on: :member
    post :improving, on: :collection
    get  :trade,     on: :member
  end

  root to: "home#index"

end

app/models/trade.rb
class Trade < ActiveRecord::Base
  belongs_to :player
  belongs_to :card
  default_scope { where(closed: false) } 

end

app/controllers/trades_controller.rb
# encoding: utf-8

class TradesController < ApplicationController
before_action :authenticate_user!
before_action :preparing
include TradesHelper

  def index
    @trades = Trade.all
  end

  def create
    return if(error?(verify_creating(@player,params),:root))
    @player.trades.create(card_id: params[:card_id],price: params[:price])
    Card.find(params[:card_id]).update_attribute(:player_id, nil)
    redirect_to :root, notice: "カードを交易に出しました"
  end

  def destroy
    trade = Trade.find(params[:id])
    Card.find(trade.card_id).update_attribute(:player_id, @player.id)
    trade.destroy
    redirect_to :root
  end

  def edit
    @trade = Trade.find(params[:id])
  end

  def update
    trade_params = params.require(:trade).permit(:price)
    @trade = Trade.find(params[:id])
    @trade.update(trade_params)
    redirect_to :root
  end

  def buy
    trade = Trade.find(params[:id])
    return if(error?(verify_buying(@player,trade),:trades))
    trade.player.money.add(trade.price)
    @player.money.sub(trade.price)
    trade.card.update_attribute(:player_id, @player.id)
    trade.update_attribute(:closed, true)
    redirect_to :root
  end

end

app/helpers/trades_helper.rb
module TradesHelper

  def verify_creating(player, params)
  end

  def verify_buying(player, trade)
  end

end

app/views/trades/_trade.html.slim
- card = trade.card
div class = "#{card.type}"
  span class="#{card.era_status}" 
    =card.name 
  | Lv.#{card.level} (#{card.exp}/#{[20,60,100][card.level-1]})
  br
  - if(card.type == :army)
    span pow #{card.power}
  p 価格: #{trade.price}
  - if(trade.player == @player)
    =link_to "修正", edit_trade_path(card.trade)
    =link_to "キャンセル", trade_path(card.trade), method: :delete
  - else
    = button_to "購入", buy_trade_path(trade)

app/views/trades/edit.html.slim
=render partial: @trade.card
p 現在の取引価格: #{@trade.price}
=form_for @trade do |f|
  =f.number_field :price
  =f.submit "修正"

app/views/trades/index.html.slim
h1 交易一覧
= link_to "戻る", :root

div class="trade"
  =render partial: :trade, collection: @trades